on: [push]
name: CI
jobs:
  tests:
    name: tests / stack
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # TODO: add more os
        resolver:
          - "lts-17"
          - "lts-16"
          - "lst-14"

    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: 'latest'

      - uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ matrix.os }}-${{resolver}}

      - name: Build
        run: stack build --resolver=${{ matrix.resolver }} --test --no-run-tests

      - name: Test
        run: stack test --resolver=${{ matrix.resolver }}
